language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(cat ./coverage/lcov.info | ./node_modules/.bin/coveralls)
